### ISSUE TITLE
Ubiquitous Documentation

### ISSUE THREAD

**Issue by morgantic** [meza/minecraft-mod-manager#367]
### What happened?

The documentation doesn't specifiy how SCAN chooses amongst modrinth and curseforge for mods that are available on both platforms, if you don't specify a preferred option.

### What did you expect to happen?

I expected to find how the tool handles the choice if a mod that's found by scan is found on curseforge and modrinth.

### Which command did you run?

-

### Operating System

Windows

### What version of MMM are you running?

-

### I have updated

- [X] I swear I have tried it with the latest version!

**Comment by meza** [comment]
<img width="682" alt="image" src="https://github.com/meza/minecraft-mod-manager/assets/211977/5f311d2f-b943-4fe5-b6b0-1379e466ef30">

You can specify your preferences with `-p`

**Comment by morgantic** [comment]
Yes, but you can omit the flag, at least it doesn't complain then, and for me it's not clear what choice it makes, then.
